version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  client:
    build: ./client
    depends_on:
      - cache
    ports: 
      - 3000:3000
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
  server:
    build: ./server
    depends_on:
      - cache
      - client
    ports: 
      - 4000:4000
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
volumes:
  cache:
    driver: local
